// import burger from './modules/burger.js';
import phonesList from './modules/phones-list.js';
import catalog from './modules/catalog.js';
import cart from './modules/cart.js';
import swiper from './modules/slider.js';
import productSlider from './modules/product-slider.js';
import mixItUp from './modules/mixitup.js';
import tabs from './modules/tabs.js';
import video from './modules/video.js';
import sliderVideo from './modules/slider-video.js';
// import menuActive from './modules/menuActive.js';
// import modal from './modules/modal.js';
// import accordion from './modules/accordion-max.js';
// import showHideBlock from './modules/show-hide-block.js';